export const LANGUAGES = [
    { name: 'English', nativeName: 'English', region: 'Worldwide', code: 'en' },
    { name: 'Spanish', nativeName: 'Español', region: 'Americas & Europe', code: 'es' },
    { name: 'French', nativeName: 'Français', region: 'Europe & Africa', code: 'fr' },
    { name: 'Japanese', nativeName: '日本語', region: 'Asia', code: 'ja' },
    { name: 'Mandarin', nativeName: '普通话', region: 'Asia', code: 'zh' },
    { name: 'Hindi', nativeName: 'हिन्दी', region: 'Asia', code: 'hi' },
    { name: 'Arabic', nativeName: 'العربية', region: 'Middle East & Africa', code: 'ar' },
    { name: 'Bengali', nativeName: 'বাংলা', region: 'Asia', code: 'bn' },
    { name: 'Russian', nativeName: 'Русский', region: 'Europe & Asia', code: 'ru' },
    { name: 'Portuguese', nativeName: 'Português', region: 'Americas & Europe', code: 'pt' },
    { name: 'Indonesian', nativeName: 'Bahasa Indonesia', region: 'Asia', code: 'id' },
    { name: 'German', nativeName: 'Deutsch', region: 'Europe', code: 'de' },
    { name: 'Korean', nativeName: '한국어', region: 'Asia', code: 'ko' },
    { name: 'Turkish', nativeName: 'Türkçe', region: 'Asia & Europe', code: 'tr' },
    { name: 'Italian', nativeName: 'Italiano', region: 'Europe', code: 'it' },
    { name: 'Dutch', nativeName: 'Nederlands', region: 'Europe', code: 'nl' },
    { name: 'Polish', nativeName: 'Polski', region: 'Europe', code: 'pl' },
];
