export const LANGUAGES = [
    { name: 'English', nativeName: 'English', region: 'Worldwide' },
    { name: 'Mandarin', nativeName: '普通话', region: 'Asia' },
    { name: 'Hindi', nativeName: 'हिन्दी', region: 'Asia' },
    { name: 'Spanish', nativeName: 'Español', region: 'Americas & Europe' },
    { name: 'French', nativeName: 'Français', region: 'Europe & Africa' },
    { name: 'Arabic', nativeName: 'العربية', region: 'Middle East & Africa' },
    { name: 'Bengali', nativeName: 'বাংলা', region: 'Asia' },
    { name: 'Russian', nativeName: 'Русский', region: 'Europe & Asia' },
    { name: 'Portuguese', nativeName: 'Português', region: 'Americas & Europe' },
    { name: 'Urdu', nativeName: 'اردو', region: 'Asia' },
    { name: 'Indonesian', nativeName: 'Bahasa Indonesia', region: 'Asia' },
    { name: 'German', nativeName: 'Deutsch', region: 'Europe' },
    { name: 'Japanese', nativeName: '日本語', region: 'Asia' },
    { name: 'Nigerian Pidgin', nativeName: 'Naija', region: 'Africa' },
    { name: 'Marathi', nativeName: 'मराठी', region: 'Asia' },
    { name: 'Telugu', nativeName: 'తెలుగు', region: 'Asia' },
    { name: 'Turkish', nativeName: 'Türkçe', region: 'Asia & Europe' },
    { name: 'Tamil', nativeName: 'தமிழ்', region: 'Asia' },
    { name: 'Yue Chinese', nativeName: '粵語', region: 'Asia' },
    { name: 'Vietnamese', nativeName: 'Tiếng Việt', region: 'Asia' },
    { name: 'Tagalog', nativeName: 'Tagalog', region: 'Asia' },
    { name: 'Wu Chinese', nativeName: '吴语', region: 'Asia' },
    { name: 'Korean', nativeName: '한국어', region: 'Asia' },
    { name: 'Iranian Persian', nativeName: 'فارسی', region: 'Asia' },
    { name: 'Hausa', nativeName: 'Hausa', region: 'Africa' },
    { name: 'Egyptian Spoken Arabic', nativeName: 'اللهجة المصرية', region: 'Middle East & Africa' },
    { name: 'Swahili', nativeName: 'Kiswahili', region: 'Africa' },
    { name: 'Javanese', nativeName: 'Basa Jawa', region: 'Asia' },
    { name: 'Italian', nativeName: 'Italiano', region: 'Europe' },
    { name: 'Dutch', nativeName: 'Nederlands', region: 'Europe' },
    { name: 'Polish', nativeName: 'Polski', region: 'Europe' },
];
