export const LANGUAGES = [
    { name: 'English', nativeName: 'English', region: 'Worldwide', code: 'en' },
    { name: 'Mandarin Chinese', nativeName: '普通话', region: 'Asia', code: 'zh' },
    { name: 'Hindi', nativeName: 'हिन्दी', region: 'Asia', code: 'hi' },
    { name: 'Spanish', nativeName: 'Español', region: 'Americas & Europe', code: 'es' },
    { name: 'French', nativeName: 'Français', region: 'Europe & Africa', code: 'fr' },
    { name: 'Standard Arabic', nativeName: 'العربية', region: 'Middle East & Africa', code: 'ar' },
    { name: 'Bengali', nativeName: 'বাংলা', region: 'Asia', code: 'bn' },
    { name: 'Russian', nativeName: 'Русский', region: 'Europe & Asia', code: 'ru' },
    { name: 'Portuguese', nativeName: 'Português', region: 'Americas & Europe', code: 'pt' },
    { name: 'Urdu', nativeName: 'اردو', region: 'Asia', code: 'ur' },
    { name: 'Indonesian', nativeName: 'Bahasa Indonesia', region: 'Asia', code: 'id' },
    { name: 'German', nativeName: 'Deutsch', region: 'Europe', code: 'de' },
    { name: 'Japanese', nativeName: '日本語', region: 'Asia', code: 'ja' },
    { name: 'Turkish', nativeName: 'Türkçe', region: 'Asia & Europe', code: 'tr' },
    { name: 'Vietnamese', nativeName: 'Tiếng Việt', region: 'Asia', code: 'vi' },
    { name: 'Tamil', nativeName: 'தமிழ்', region: 'Asia', code: 'ta' },
    { name: 'Korean', nativeName: '한국어', region: 'Asia', code: 'ko' },
    { name: 'Persian (Farsi)', nativeName: 'فارسی', region: 'Middle East', code: 'fa' },
    { name: 'Italian', nativeName: 'Italiano', region: 'Europe', code: 'it' },
    { name: 'Swahili', nativeName: 'Kiswahili', region: 'Africa', code: 'sw' }
];